### PR TITLE
iOS Seek Bar

### PR DESCRIPTION
**Pull request by YaarPatandarAA**
This should add the seek bar ability on iOS.

### CODE REVIEW

**Comment by YaarPatandarAA** [comment]
Close #14

**Comment by YaarPatandarAA** [comment]
Forgot to make the duration update based on Seek

**Comment by YaarPatandarAA** [comment]
Forgot to make the duration update based on Seek

**Comment by YaarPatandarAA** [comment]
@gaucidaniel This should be good to go, updated it with the seek elapsed time update.

**Comment by gaucidaniel** [comment]
Looks good to me, great work as always!

**Pull request merged**
